#内置tomcat 配置
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


#数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #数据源类型 Hikari
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000   #等待连接池分配连接的最大时长  毫秒
      minimum-idle: 5             #最小连接数
      maximum-pool-size: 20       #最大连接数
      auto-commit: true           #自动提交
      idle-timeout: 600000        #连接超时的最大时长 超时则被释放 10min
      pool-name: DataSourceHikariCP  #连接池名字
      max-lifetime: 1800000       #连接的生命时长 30min
      connection-test-query: SELECT 1

#mybatis配置
mybatis:
  type-aliases-package: com.imooc.pojo       #所有pojo类所在包路径
  mapper-locations: classpath:mapper/*.xml   #mapper映射文件  classpath指的是所有的resources目录
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis mapper配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false #在进行数据库操作的时候， 判断表达式 username != null 是否追加 username != ''
  identity: MYSQL #数据库方言